version: 1.0.{build}

image: Visual Studio 2019

before_build:
  - cmd: mkdir cmake-build-debug & cd cmake-build-debug
  - cmd: cmake ../ -G "Visual Studio 16 2019"
  - cmd: cd ..

build:
  project: cmake-build-debug/CppTest.sln
  verbosity: quiet