version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
platform: x86
clone_folder: C:\Code\VCTest
install:
- cmd: >-
    cd C:\Tools\vcpkg
    .\bootstrap-vcpkg.bat
    .\vcpkg.exe integrate install
    .\vcpkg.exe install openssl-windows --triplet x86-windows
    .\vcpkg.exe install freeglut --triplet x86-windows
    .\vcpkg.exe install glog --triplet x86-windows
    .\vcpkg.exe install duilib --triplet x86-windows
    .\vcpkg.exe install cppunit --triplet x86-windows
cache: C:\Tools\vcpkg\installed\
before_build:
- cmd: cd C:\Code\VCTest
build:
  project: VCTest.sln
  parallel: true
  verbosity: detailed