CC := g++
RM := rm -f
LIBS =

all: main0001 main0003

clean:
	$(RM)  bin/*.exe

main0001: main0001.cpp
	$(CC) main0001.cpp -o ../bin/main0001
main0003: main0003.cpp
	$(CC) main0003.cpp -o ../bin/main0003