name: Build

on: 
  push:
  pull_request:
    branches: [master]

jobs:
  x86-debug:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x86

    # https://learn.microsoft.com/zh-cn/vcpkg/get_started/get-started?pivots=shell-cmd
    - name: Set Environment Variable
      run: |

    - name: Cache vcpkg and dependencies
      uses: actions/cache@v3
      with:
        path: C:/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    # https://github.com/dgcor/Diabolika/blob/0d83d46c3e86cb31ffcbc52baa0a81cf1531471c/.github/workflows/deploy_windows.yml#L43
    - name: CMake build
      run: |
        cmake --preset x86-debug
        cmake --build --preset x86-debug

  x64-debug:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64

    # https://learn.microsoft.com/zh-cn/vcpkg/get_started/get-started?pivots=shell-cmd
    - name: Set Environment Variable
      run: |

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: C:/vcpkg
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.json') }}

    # https://github.com/dgcor/Diabolika/blob/0d83d46c3e86cb31ffcbc52baa0a81cf1531471c/.github/workflows/deploy_windows.yml#L43
    - name: CMake build
      run: |
        cmake --preset x64-debug
        cmake --build --preset x64-debug