name: Build

on: 
  push:
  pull_request:
    branches: [master]

env:
  SOLUTION_FILE_PATH: ./VCTest.sln
  BUILD_CONFIGURATION: Debug

jobs:
  VS2022-Build:
    runs-on: windows-latest

    strategy:
      matrix:
        TARGET_PLATFORM: [x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      with:
        msbuild-architecture: x64

    - name: Cache vcpkg and dependencies
      uses: actions/cache@v2
      with:
        path: |
          C:\vcpkg\installed
        key: ${{ runner.os }}-${{ hashFiles('vcpkg.txt') }}

    - name: Build dependencies
      run: |
          vcpkg integrate install
          vcpkg install --triplet x86-windows --allow-unsupported @vcpkg.txt

    - name: Build
      shell: cmd
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }},Platform=${{ matrix.TARGET_PLATFORM }}