name: Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        preset: [ "linux-x64-debug", "linux-x64-release" ]

    steps:
      - uses: actions/checkout@v3

      - name: Install GTK
        run: sudo apt-get install -y libgtk-3-dev

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: CMake Configure Build And Test
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}
          ctest --preset ${{ matrix.preset }}

  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        preset: [ "macos-x64-debug", "macos-x64-release" ]

    steps:
      - uses: actions/checkout@v3

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg integrate install

      - name: Install GTK
        run: brew install gtk+3 libffi

      # https://github.com/microsoft/vcpkg/discussions/30813
      - name: Install autoconf for cppunit build
        run: brew install libtool automake

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: CMake Configure Build And Test
        run: |
          export VCPKG_INSTALLATION_ROOT=./vcpkg
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}
          ctest --preset ${{ matrix.preset }}

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        preset: [ "windows-x64-debug", "windows-x64-release", "windows-x64-mingw-debug", "windows-x64-mingw-release" ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: CMake Configure Build And Test
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}
          ctest --preset ${{ matrix.preset }}
