name: Coverity Scan Report

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install some dependencies
        run: |
          # https://blog.csdn.net/xiong_xin/article/details/148389435
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y libgtk-3-dev
          # https://github.com/freeglut/freeglut
          sudo apt-get install libgl-dev libglu1-mesa-dev libx11-dev libxrandr-dev libxi-dev

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: Configure CMake
        run: cmake --preset linux-x64-release

      - uses: vapier/coverity-scan-action@v1.8.0
        with:
          project: 'jiangxincode/CppTest'
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          email: 'jiangxinnju@163.com'
          build_language: 'cxx'
          build_platform: 'linux64'
          command: 'cmake --build --preset linux-x64-release'
      - name: Print build-log.txt
        run: |
          cat /home/runner/work/CppTest/CppTest/cov-int/build-log.txt