name: Coverity Scan Report

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GTK
        run: sudo apt-get install -y libgtk-3-dev

      - name: Configure CMake
        run: cmake --preset linux-x64-release

      - uses: vapier/coverity-scan-action@v1.6.0
        with:
          project: 'jiangxincode/CppTest'
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          email: 'jiangxinnju@163.com'
          build_language: 'cxx'
          build_platform: 'linux64'
          command: 'cmake --build --preset linux-x64-release'
      - name: Print build-log.txt
        run: |
          cat /home/runner/work/CppTest/CppTest/cov-int/build-log.txt