name: Sonar Report
on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        preset: [ "linux-x64-release" ]

    env:
      BUILD_WRAPPER_OUT_DIR: bw_output

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install some dependencies
        run: |
          # https://blog.csdn.net/xiong_xin/article/details/148389435
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y libgtk-3-dev
          # required by freeglut
          sudo apt-get install -y libgl-dev libglu1-mesa-dev libx11-dev libxrandr-dev libxi-dev
          # cppunit need autoconf: https://github.com/microsoft/vcpkg/discussions/30813
          sudo apt-get install -y autoconf autoconf-archive automake libtool

      - name: Cache vcpkg
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v8

      - name: Build
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build --preset ${{ matrix.preset }}

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
