name: Sonar Report
on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install some dependencies
        run: |
          sudo apt-get install -y libgtk-3-dev
          # https://github.com/freeglut/freeglut
          sudo apt-get install libgl-dev libglu1-mesa-dev libx11-dev libxrandr-dev libxi-dev

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/out/build/${{ matrix.preset }}/vcpkg_installed
          key: "${{ runner.os }}-${{ matrix.preset }}-${{ hashFiles('vcpkg.json') }}"

      - name: Configure CMake
        run: cmake --preset linux-x64-release

      - name:  Install sonar-scanner and build-wrapper
        uses: sonarsource/sonarcloud-github-c-cpp@v2

      - name: Build SonarCloud Scan
        working-directory: ${{github.workspace}}
        run: |
          build-wrapper-linux-x86-64 --out-dir bw_output cmake --build --preset linux-x64-release
          sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}